name: Conda 
description: Miniconda ready for Bioinformatics
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: miniconda
        action: ExecuteBash
        inputs:
          commands:
            # Download conda and install for ec2-user
            - |
              su - ec2-user \
                -c "wget -O miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
                    bash miniconda.sh -b -p /home/ec2-user/.conda && \
                    rm miniconda.sh"
            # Initialise conda for ec2-user
            - |
              su - ec2-user \
                -c "/home/ec2-user/.conda/bin/conda init"
            # Update base conda version
            - |
              su - ec2-user \
               -c "conda update -n base conda -y"
            # Set default channels for ec2-user
            # Defaults remains at the top of the channel list
            - |
              su - ec2-user \
                -c "conda config --append channels bioconda && \
                    conda config --append channels conda-forge"