name: sync-conda-component-env-yamls

inputs:
  tag_name:
    description: name of the release tag
    required: true
  ssm_s3_pc_config_root:
    description: The ssm parameter key to the s3 bucket containing the configuration files
    required: true

description: |
  Upload appropriate files to the s3 bucket ready for creation of the ami.
  Each of the conda env components requires a conda env file found on s3.
  These must exist prior to the creation of the component objects.

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Install requirements
        sudo apt-get update
        sudo apt-get install -y \
          awscli \
          jq \
          rsync

        # Get config root with ssm-parameter key
        s3_config_root="$(aws ssm get-parameter --name "${{ inputs.ssm_s3_pc_config_root }}" | {
                          jq --raw-output '.Parameter.Value'
                        })"

        # Now extend folder with the version/tag
        s3_config_version="${s3_config_root}/${{ inputs.tag_name }}"

        # Initialise folder ready for upload
        s3_sync_files_dir="release_dir"
        mkdir -p "${s3_sync_files_dir}"

        # Add folders to upload to s3
        rsync --archive slurm/ "${s3_sync_files_dir}/slurm/"
        rsync --archive toil/ "${s3_sync_files_dir}/toil/"
        rsync --archive cromwell/ "${s3_sync_files_dir}/cromwell/"
        rsync --archive bcbio/ "${s3_sync_files_dir}/bcbio/"

        # Now run sync command
        aws s3 sync "${s3_sync_files_dir}/" "${s3_config_version}/"

        # Delete sync folder
        rm -rf "${s3_sync_files_dir}/"
