name: Base 
description: Parallelcluster base software and dependencies
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: base-extras
        action: ExecuteBash
        inputs:
          commands:
            # Update yum then rest
            - |
              yum update -y -q
            # Reset yum
            - |
              # Clean rpm cache first
              if [[ -d "/var/lib/rpm/" ]]; then
                rm -f /var/lib/rpm/__db*
                logger -s "Cleaning rpm cache"
              fi
              # Then clean yum
              yum clean all
              logger -s "Cleaning yum"
              rm -rf /var/cache/yum
            # Update yum, install dev tools
            - |
              yum update -y -q
              # Install devtools
              yum groups mark install "Development Tools"
              yum update -y -q
              yum groupinstall -y 'Development Tools'
            # Change timezone to Australia/Melbourne
            - |
              TIMEZONE="Australia/Melbourne"
              timedatectl set-timezone "${TIMEZONE}"
            # Install basics
            - |
              yum update -y -q
              yum install -y -q \
                amazon-linux-extras \
                tmux \
                htop \
                wget \
                curl \
                file \
                git
            # Install latest aws cli
            - |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install
            # Install packages inside amazon-linux-extras
            - |
              amazon-linux-extras install -y -q \
                epel \
                vim \
                docker \
                lustre2.10 \
                livepatch \
                R3.4 \
                ruby2.4 \
                golang1.11 \
                rust1 \
                java-openjdk11
            # Install python3 and pip3
            # Install aws-parallelcluster
            - |
              yum install -y -q \
                epel-release
              yum install -y -q \
                python3 python3-pip
              python3 -m pip install --upgrade pip
              python3 -m pip install aws-parallelcluster
            ## Install mysql for slurm accounting
            - |
              yum install -y -q \
                mysql
            ## Install latest amazon-ssm-agent
            - |
              systemctl stop amazon-ssm-agent
              systemctl disable amazon-ssm-agent
              wget --output-document amazon-ssm-agent.rpm \
                https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
              rpm \
                --install \
                --force \
                --upgrade \
                --replacepkgs amazon-ssm-agent.rpm
              rm amazon-ssm-agent.rpm
              systemctl enable amazon-ssm-agent
              systemctl start amazon-ssm-agent
            ## Add ec2-user to docker
            - |
              usermod -a -G docker ec2-user